
server:
  port: 8088
eureka:
  client:
    service-url:
      # \u586B\u5199\u6CE8\u518C\u4E2D\u5FC3\u670D\u52A1\u5668\u5730\u5740
      defaultZone: http://localhost:8081/eureka
spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lyh-liyunhui/springcloud-config.git
  search-paths: myconfig
